_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 17
                - 23
                - 55
            "4": 3.9.13
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
